### ISSUE TITLE
Dashboard Creation

### ISSUE THREAD

**Issue by TealTurtle** [dsantosp12/Textrade#14]
-Include Wishlist
-Include Books in transit
-Include Suggestions
-Include Trades in progress

etc...reference mockup

**Comment by ninapetrop** [comment]
I'm wondering how important a wish list is. We already have a few features that automatically generate a "wish list".
<ol><li>We know the books that users want to get in return for a trade</li><li>When users search for a book and apply filters (or apply no filters) there is a check box to "receive a notification if a title enters the market that has the above criteria</li></ol>

Books in transit doesn't seem necessary now based on the current set up with the truck, drop-offs, etc.
