### ISSUE TITLE
"Rent Page: Rent your book out(if no account send to login page):Step1"

### ISSUE THREAD

**Issue by TealTurtle** [dsantosp12/Textrade#16]
refer to mock up

**Comment by ninapetrop** [comment]
Is this something that can be regulated with a back end "if" statement. There is a login button at the navbar, if the user isn't already logged and tries to press "rent you book" or "search for books" in it should spit them to the "log-in" page.

Rent home page already includes a line to create account.

**Comment by dsantosp12** [comment]
@ninapetrop I think this is useless now because everything will be done through the dashboard. Closing it.
