### ISSUE TITLE
Give a discription or image to provide a book quality standard to the customers when thery are selecting the quality of their book

### ISSUE THREAD

**Issue by TealTurtle** [dsantosp12/Textrade#35]
At first i was thinking it would be good to provice the little question mark next to that category, but i think it would be better to put it right on the page so people can see it immediately and be more aware of our standards.

**Comment by ninapetrop** [comment]
New checkbox to signal is notes/text has been written inside of the book. Each selector has a hint to classify the condition 
ex.

<option>Very Good - Minimal wear on cover, otherwise perfect</option>
<option>Good - Some wear on the cover, spine, and pages</option>
