### ISSUE TITLE
Insert a file a complaint link under the chat box when users are chatting (rent and trade)

### ISSUE THREAD

**Issue by TealTurtle** [dsantosp12/Textrade#36]
Feel free to incorporate this feature anywhere else you think it would be useful, but try to keep is separate from the comments section so they wont get confused. Maybe incorporate it into the Dashboard...it would be a good place to put a link to the  the comment also...

**Comment by ninapetrop** [comment]
This should probably just be an option from a dropdown menu in a generic "contact us" form. I haven't taken any steps towards a chat box yet, I'm not sure if @dsantosp12 has ... we can catch up on this at our next meeting.
