### ISSUE TITLE
Book search API integrated

### ISSUE THREAD

**Issue by dsantosp12** [dsantosp12/Textrade#39]
I just integrated a free, so far, API from Google that let me search for books and get the information that we need to save the books in our database. With that being said, the forms for the renting can also be optimized to only ask for the ISBN, condition of the books, picture, and comments, which is optional.
@ninapetrop you can close this issue right after you read it. :+1:

**Comment by ninapetrop** [comment]
What a champ!

**Comment by TealTurtle** [comment]
you go Daniel! :D
