### ISSUE TITLE
The Team - names, titles, sentence

### ISSUE THREAD

**Issue by ninapetrop** [dsantosp12/Textrade#61]
Chris,

I need:
<ol><li>Full name</li><li>Position</li><li>One sentence about whatever you want (i.e about you, your job, your hobbies)</li></ol>

**Comment by dsantosp12** [comment]
We need this hehehehe @TealTurtle

**Comment by dsantosp12** [comment]
This also still a placeholder @ninapetrop  @TealTurtle  @Christophertextrade1

**Comment by ninapetrop** [comment]
yep, @Christophertextrade1 I need you to send us your position and sentence for this page.
