### ISSUE TITLE
Contact Page - Create

### ISSUE THREAD

**Issue by ninapetrop** [dsantosp12/Textrade#64]
@TealTurtle what's the contact info for Textrade

are there going to be .. how do you say  it... 'sub-emails'. i.e
<ul><li>payments@textrade.com</li><li>accounts@textrade.com</li><ul>

**Comment by TealTurtle** [comment]
Oh...I hadn't thought about that. So we just have the  General email that goes with the domain name. We would more for the other ones

Sent on the new Sprint Network

----- Reply message -----
